#!/usr/bin/env bash
# Display a hierarchical tree of all running processes for all users
ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,cmd --sort=ppid | awk '
NR==1 {print; next}
{process[$2]=$0; parent[$3]=parent[$3] " " $2}
END {print_tree(0, 0)}

function print_tree(ppid, level) {
    for (pid in process) {
        if (ppid == 0 || index(parent[ppid], pid)) {
            printf "%s%s\n", substr("  |", 1, level*2), process[pid]
            print_tree(pid, level + 1)
        }
    }
}'
